SELECT a.TITLE, a.BOARD_ID,REPLY_ID,b.WRITER_ID,b.CONTENTS,LEFT(b.CREATED_DATE,11) as CREATED_DATE
    FROM USED_GOODS_BOARD AS a
        INNER JOIN USED_GOODS_REPLY AS b
        ON a.BOARD_ID = b.BOARD_ID
        WHERE LEFT(a.CREATED_DATE,7) = DATE_FORMAT(now(),'2022-10')
        ORDER BY b.CREATED_DATE ASC, TITLE ASC;